let actionTypes = {
    LOGIN_LOADING: 'LOGIN_LOADING', 
    ARTICLES_LOADING: 'ARTICLES_LOADING', 
    SET_TOKEN: 'SET_TOKEN',
    DELETE_TOKEN: 'DELETE_TOKEN',
    SET_LOGIN_ERROR_MESSAGE: 'SET_LOGIN_ERROR_MESSAGE',
    SET_ARTICLES_ERROR_MESSAGE: 'SET_ARTICLES_ERROR_MESSAGE',
    SET_ARTICLES: 'SET_ARTICLES',
    SET_HAS_MORE: 'SET_HAS_MORE',
    SET_FILTERED_ARTICLES : 'SET_FILTERED_ARTICLES',
}

export default actionTypes;